# -*- coding: utf-8 -*-
"""title or sms.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QV4ZzSmsz47AQXhqDFJxyScNVwFSdDaZ

Разделение заголовочных слов и их помет

"""

import re
from bs4 import BeautifulSoup
from typing import Dict, List, Tuple, Optional
import unicodedata



def parse_dictionary_entry(entry_html: str) -> Dict[str, any]:

    soup = BeautifulSoup(entry_html, 'html.parser')

    # Ищем первый элемент <b>, так как заголовок всегда в нем.
    headword_element = soup.find('b')
    if not headword_element:
        return {'headword': None, 'notes': []}

    headword_text = headword_element.get_text(strip=True)

    notes = []

    # Траверсируем все последующие элементы и текстовые узлы после headword_element
    # до тех пор, пока не встретим следующий 'b' тег или конец абзаца.
    current_element = headword_element.next_element
    while current_element and current_element.name != 'b': # Останавливаемся, если дошли до следующего bold-тега
        if current_element.name == 'i':
            note_text = current_element.get_text(strip=True)
            if note_text:
                notes.append(note_text)
        elif isinstance(current_element, str): # Обрабатываем текстовые узлы (NavigableString)
            text = current_element.strip()
            if text:
                # Ищем слова, выделенные звездочками или в скобках
                pattern = r'(\*[^\*]+\*)|(\([^)]+\))'
                found_notes = re.findall(pattern, text)
                for note_tuple in found_notes:
                    for note in note_tuple:
                        if note:
                            notes.append(note.strip('*() '))
        current_element = current_element.next_element # Переходим к следующему элементу/текстовому узлу

    return {
        'headword': headword_text,
        'notes': notes
    }

def extract_headwords_and_notes_from_html(html_content: str) -> List[Dict[str, any]]:

    soup = BeautifulSoup(html_content, 'html.parser')

    entries = []
    paragraphs = soup.find_all('p')

    for p in paragraphs:
        # Проверяем, есть ли <b> элемент внутри абзаца, независимо от того, где он находится
        if p.find('b'):
            # Это начало словарной статьи
            entry_data = parse_dictionary_entry(str(p))
            if entry_data['headword']:
                entries.append(entry_data)

    return entries

def load_html_from_file(filepath: str) -> Optional[str]:

    try:
        with open(filepath, 'r', encoding='utf-8') as f:
            return f.read()
    except UnicodeDecodeError:
        # Если UTF-8 не сработал, пробуем другую кодировку, например windows-1251
        try:
            with open(filepath, 'r', encoding='windows-1251') as f:
                return f.read()
        except Exception as e:
            print(f"Произошла ошибка при чтении файла с кодировкой windows-1251: {e}")
            return None
    except FileNotFoundError:
        print(f"Ошибка: Файл не найден по пути: {filepath}")
        return None
    except Exception as e:
        print(f"Произошла ошибка при чтении файла: {e}")
        return None

"""### Пример использования функций"""

# Укажите путь к вашему HTML-файлу
html_file_path = '/content/dictionary.htm' # Замените на фактический путь к вашему файлу

html_content = load_html_from_file(html_file_path)

if html_content:
    all_entries = extract_headwords_and_notes_from_html(html_content)

    if all_entries:
        print(f"Найдено {len(all_entries)} словарных статей:")
        for i, entry in enumerate(all_entries[:5]): # Выводим первые 5 для примера
            print(f"\nСтатья {i+1}:")
            print(f"  Заголовок: {entry['headword']}")
            print(f"  Пометы: {entry['notes']}")
        if len(all_entries) > 5:
            print(f"...и еще {len(all_entries) - 5} статей.")
    else:
        print("Словарные статьи не найдены в файле.")
else:
    print("Не удалось загрузить HTML-файл.")