# -*- coding: utf-8 -*-
"""Untitled8.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dxsyrrdPxiJM7St0qYU2PzLVH0nF25h9
"""

!pip install py7zr python-docx beautifulsoup4 -q

from google.colab import files
import py7zr
import os
import json
import re
from bs4 import BeautifulSoup

print("1. Загрузите архив 7z (например, Output_1-19_html.7z)")
print("2. Загрузите файл Указателя источников (DOCX)")
uploaded = files.upload()

import os
import json
import re
import docx
from bs4 import BeautifulSoup
from google.colab import files

def get_source_ciphers(sources_path):
    """Извлекает шифры из указателя источников."""
    doc = docx.Document(sources_path)
    ciphers = set()
    cipher_split = re.compile(r'\s+[—–-]\s+')
    for para in doc.paragraphs:
        text = para.text.strip()
        parts = cipher_split.split(text)
        if len(parts) > 1:
            c = parts[0].replace('*', '').strip()
            if 0 < len(c) < 40: ciphers.add(c)
    return sorted(list(ciphers), key=len, reverse=True)

def parse_html_article(html_path, ciphers_regex_str):
    """Парсит один HTML файл и выделяет цитаты и источники."""
    try:
        with open(html_path, 'r', encoding='utf-8') as f:
            soup = BeautifulSoup(f, 'html.parser')
            text = soup.get_text(separator=" ", strip=True)

        bib_tail = r'(?:[\s\dIVXLCDM\.,\-()|/]|с\.|т\.|ч\.|кн\.|вып\.)*?'
        full_pattern = rf'({ciphers_regex_str}){bib_tail}\.'

        matches = list(re.finditer(full_pattern, text))
        results = []
        last_end = 0

        for match in matches:
            start, end = match.span()
            quote_part = text[last_end:start].strip()
            quote_part = re.sub(r'^[,\.;\s]+|[,\s]+$', '', quote_part)

            results.append({
                "quote_zone": quote_part,
                "source": match.group(0).strip()
            })
            last_end = end

        return results
    except Exception as e:
        return []

# --- НАСТРОЙКА ПУТЕЙ ---

# 1. Путь к указателю в корне /content/
sources_path = '/content/Указатель_источников_Сл_XVIII_16_04_2025.docx'

# 2. Путь к уже существующей папке с выпусками
base_path = "/content/Output_1-19_html"

print("🔍 Шаг 1: Загрузка базы шифров...")
if not os.path.exists(sources_path):
    print(f"❌ Файл не найден: {sources_path}")
else:
    ciphers_list = get_source_ciphers(sources_path)
    escaped_ciphers = [re.escape(c) for c in ciphers_list]
    ciphers_regex_str = '|'.join(escaped_ciphers)
    print(f"✅ База готова: {len(ciphers_list)} шифров.")

    print(f"🚀 Шаг 2: Обработка папки {base_path}...")
    final_output = []
    file_count = 0

    # Рекурсивно заходим во все подпапки (Выпуск 1, Выпуск 2 и т.д.)
    for root, dirs, files_list in os.walk(base_path):
        html_files = [f for f in files_list if f.endswith(".html")]

        if not html_files:
            continue

        current_volume = os.path.basename(root)

        for filename in html_files:
            file_path = os.path.join(root, filename)
            article_results = parse_html_article(file_path, ciphers_regex_str)

            if article_results:
                final_output.append({
                    "volume": current_volume,
                    "word": filename.replace(".html", ""),
                    "segments": article_results
                })

            file_count += 1
            if file_count % 500 == 0:
                print(f"📊 Обработано {file_count} статей...")

    # 3. Сохранение результата
    output_json = 'full_dictionary_1-19.json'
    with open(output_json, 'w', encoding='utf-8') as f:
        json.dump(final_output, f, ensure_ascii=False, indent=2)

    print(f"\n🏆 ГОТОВО! Обработано файлов: {file_count}")
    print(f"Итоговый файл: {output_json}")
    files.download(output_json)

import os
import json
import re
import docx
import py7zr
from bs4 import BeautifulSoup
from google.colab import files

# --- ФУНКЦИИ ---

def get_source_ciphers(sources_path):
    doc = docx.Document(sources_path)
    ciphers = set()
    cipher_split = re.compile(r'\s+[—–-]\s+')
    for para in doc.paragraphs:
        text = para.text.strip()
        parts = cipher_split.split(text)
        if len(parts) > 1:
            c = parts[0].replace('*', '').strip()
            if 0 < len(c) < 40: ciphers.add(c)
    return sorted(list(ciphers), key=len, reverse=True)

def parse_html_article(html_path, ciphers_regex_str):
    try:
        with open(html_path, 'r', encoding='utf-8') as f:
            soup = BeautifulSoup(f, 'html.parser')
            text = soup.get_text(separator=" ", strip=True)
        bib_tail = r'(?:[\s\dIVXLCDM\.,\-()|/]|с\.|т\.|ч\.|кн\.|вып\.)*?'
        full_pattern = rf'({ciphers_regex_str}){bib_tail}\.'
        matches = list(re.finditer(full_pattern, text))
        results = []
        last_end = 0
        for match in matches:
            start, end = match.span()
            quote_part = text[last_end:start].strip()
            quote_part = re.sub(r'^[,\.;\s]+|[,\s]+$', '', quote_part)
            results.append({"quote_zone": quote_part, "source": match.group(0).strip()})
            last_end = end
        return results
    except: return []

# --- ГЛАВНЫЙ ПРОЦЕСС ---

# 1. Проверка файлов
archive_file = '/content/Output_1-19_html.7z'
sources_path = '/content/Указатель_источников_Сл_XVIII_16_04_2025.docx'
extract_path = '/content/unpacked_dict'

if not os.path.exists(archive_file):
    print("❌ Ошибка: Архив .7z не найден в папке /content/")
elif not os.path.exists(sources_path):
    print("❌ Ошибка: Файл указателя .docx не найден")
else:
    # 2. Распаковка (если еще не распаковано)
    if not os.path.exists(extract_path):
        print("📦 Распаковка архива... (это может занять время)")
        with py7zr.SevenZipFile(archive_file, mode='r') as z:
            z.extractall(path=extract_path)
        print("✅ Распаковка завершена.")

    # 3. Подготовка базы
    print("🔍 Загрузка шифров...")
    ciphers_list = get_source_ciphers(sources_path)
    ciphers_regex_str = '|'.join([re.escape(c) for c in ciphers_list])

    # 4. Поиск и парсинг
    print(f"🚀 Обработка файлов в {extract_path}...")
    final_data = []
    total_count = 0

    for root, dirs, files_list in os.walk(extract_path):
        html_files = [f for f in files_list if f.lower().endswith(".html")]
        if not html_files: continue

        vol_name = os.path.basename(root)
        for fname in html_files:
            f_path = os.path.join(root, fname)
            res = parse_html_article(f_path, ciphers_regex_str)
            if res:
                final_data.append({
                    "volume": vol_name,
                    "word": fname.replace(".html", "").replace(".HTML", ""),
                    "segments": res
                })
            total_count += 1
            if total_count % 1000 == 0:
                print(f"📊 Обработано {total_count} файлов...")

    # 5. Итог
    output_name = 'final_dictionary_results.json'
    with open(output_name, 'w', encoding='utf-8') as f:
        json.dump(final_data, f, ensure_ascii=False, indent=2)

    print(f"\n🏆 ГОТОВО! Обработано статей: {total_count}")
    files.download(output_name)